/*
 * This source file was generated by the Gradle 'init' task
 */
package proj.flightdata

object App extends App {
  def main(args: Array[String]): Unit = {
    println(greeting())
  }



  def greeting(): String = "Hello, world!"
}
